// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBME6lKHx1Cp45AW2BWp55u2fsC4z2Kmcc',
    appId: '1:803964082325:web:5db0842671c186b24be39c',
    messagingSenderId: '803964082325',
    projectId: 'ggy-twitter-clone',
    authDomain: 'ggy-twitter-clone.firebaseapp.com',
    storageBucket: 'ggy-twitter-clone.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgTNiMxqlGY-nsuiUTUlNXGew8HJf6kMs',
    appId: '1:803964082325:android:fc1493fdf5d881024be39c',
    messagingSenderId: '803964082325',
    projectId: 'ggy-twitter-clone',
    storageBucket: 'ggy-twitter-clone.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBh_rpq7VbhQXzxRW_gRG1gLvKEXBokS6k',
    appId: '1:803964082325:ios:d4c9ea4422e679574be39c',
    messagingSenderId: '803964082325',
    projectId: 'ggy-twitter-clone',
    storageBucket: 'ggy-twitter-clone.appspot.com',
    iosClientId: '803964082325-ajfhu5l9mtubnbvfpkq3u77k0rgckdql.apps.googleusercontent.com',
    iosBundleId: 'com.example.ggyTwitterClone',
  );
}
